<?php

include('connect.php');

$sql = "SELECT `username`, `password` from `userdata`";
$result = mysqli_query($con, $sql);

$data = mysqli_fetch_array($result);

$newusername = $data['username'];
$newpassword = $data['password'];

echo "<p>Username: " . $newusername . "</p>";
echo "<p>Password: " . $newpassword . "</p>";


?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Autogenerated credentials</title>
</head>
<body>
    <h2>Login using these credentials</h2>
    <button onclick="redirectFunc()">Login</button>

    <script>
        function redirectFunc()
        {
            window.location="../";
        }
    </script>
</body>

</html>
 